#server:
#  port: 8761
#
#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false

server:
  port: 8447
  name: https://xrodrig.dnsnet.info:${server.port}
  ssl:
    enabled: true
    keyPassword: 123456
    keyStore: file:C:\Users\amgri\desenvolupament\ss-tfg-unir\xrodrigdnskeystore
    keyStorePassword: ${keystore.password}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: ${server.name}/eureka/